[build]
  publish = "."
  functions = "functions"
  
# Redirects for shorter URLs
[[redirects]]
  from = "/coredns"
  to = "/coredns-autopath/"
  status = 301

[[redirects]]
  from = "/k3s"
  to = "/self-provisioning-proxmox/"
  status = 301

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/shared/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
